const header=document.querySelector('.site-header');const menuButton=document.querySelector('.menu-button');const mobileMenu=document.querySelector('.mobile-menu');const languageButton=document.querySelector('.language');const html=document.documentElement;const body=document.body;
document.getElementById('year').textContent=new Date().getFullYear();
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>24),{passive:true});
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));mobileMenu.hidden=open});
mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.hidden=true;menuButton.setAttribute('aria-expanded','false')}));
languageButton.addEventListener('click',()=>{const fa=html.lang!=='fa';html.lang=fa?'fa':'en';html.dir=fa?'rtl':'ltr';body.classList.toggle('fa',fa);document.querySelectorAll('[data-en]').forEach(el=>el.textContent=fa?el.dataset.fa:el.dataset.en);languageButton.innerHTML=fa?'<span>EN</span><span class="active">FA</span>':'<span class="active">EN</span><span>FA</span>';});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const tilt=document.querySelector('[data-tilt]');if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){tilt.addEventListener('pointermove',e=>{const r=tilt.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;tilt.style.transform=`rotateY(${x*4}deg) rotateX(${-y*4}deg)`});tilt.addEventListener('pointerleave',()=>tilt.style.transform='');}
const dialog=document.getElementById('brief-dialog');document.getElementById('brief-button').addEventListener('click',()=>dialog.showModal());dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
const briefOutput=dialog.querySelector('.brief-output');const textarea=briefOutput.querySelector('textarea');dialog.querySelectorAll('[data-type]').forEach(button=>button.addEventListener('click',()=>{const type=button.dataset.type;textarea.value=`ROZNEX Project Brief\n\nProject type: ${type}\nBusiness / brand: \nMain goal: \nTarget audience: \nEssential features: \nPreferred launch date: \nReferences or visual direction: \nAnything else we should know: `;briefOutput.hidden=false;textarea.focus();textarea.select()}));
document.getElementById('copy-brief').addEventListener('click',async e=>{await navigator.clipboard.writeText(textarea.value);const span=e.currentTarget.querySelector('span');const original=span.textContent;span.textContent=html.lang==='fa'?'کپی شد':'Copied';setTimeout(()=>span.textContent=original,1500)});
